### ISSUE TITLE
Rearrange member listing alphabetically

### ISSUE THREAD

**Issue by linamnt** [jf-lab/jflab#26]
It's just better. I think we had it by date of joining the lab on the old website because either wordpress would just log by date added or it was maybe easier to just append to the end. I originally scraped all the info from franklandlab.com, but we definitely don't need to keep this order on the new website as it's as easy as moving the yaml data around on the new website. 

@ridaansari I will get to this at some point, so I just wanted to leave it here as a reminder, but if you wanted to, feel free, but definitely no problem if not, I will aim to do this in the next week or so.

# TODO
These are the files we need to update:

- [x] [Grad Students](https://github.com/jf-lab/jflab/blob/master/_data/grad_students.yml)
- [x] [Post-Docs](https://github.com/jf-lab/jflab/blob/master/_data/grad_students.yml)
- [x] [Research Associates](https://github.com/jf-lab/jflab/blob/master/_data/grad_students.yml)
- [x] [Staff](https://github.com/jf-lab/jflab/blob/master/_data/grad_students.yml)

Alumni seems to make sense to keep reverse chronological, but open to discussion. The PI list I think is tied to the twitter previews at the bottom, we can keep that the same for now too.

We just need to move each data block in the alphabetical order you want them displayed in each file, making sure to keep at least one blank line between each block. 

I don't know if people prefer alphabetical by first or last name. It could be kind of funny to display how many people with names that start with "A" we have.

# Alternative Solution:
 Sort by field in Jekyll rather than order written in YAML file, see [this SO answer](https://stackoverflow.com/questions/41916862/how-to-sort-yaml-using-jekyll-liquid). Main reason why this would be better is to reduce the chance for typos and breaking errors in the syntax (too much too little white space/tabbing) when having to insert of move items around, rather than appending to the end.

**Comment by linamnt** [comment]
Fixed by https://github.com/jf-lab/jflab/commit/4767985ea48797b052a6ccab32c92b20b53ccfe9

**Comment by ridaansari** [comment]
Thanks Lina! Looks good- my goodness are there a lot of first name A’s! :)

On May 21, 2020, at 1:17 PM, Lina Tran <notifications@github.com<mailto:notifications@github.com>> wrote:



Fixed by 4767985<https://github.com/jf-lab/jflab/commit/4767985ea48797b052a6ccab32c92b20b53ccfe9>
