### ISSUE TITLE
Add google sheets integration for member data + include workflow in GitHub Actions

### ISSUE THREAD

**Issue by linamnt** [jf-lab/jflab#30]
# Suggestion
Read data from a Google Sheet using Python to format the yml files.

This will allow any lab member to update their own information in the google sheet at any time, and will automate the process of updating the website via a workflow in GitHub Actions which can be triggered manually, on a schedule (e.g. every few months) and/or after any pushes to the repo.

# TODO
- [x] generate collaborative Google Sheet and populate with existing data, created credentials
- [ ] find best way to use `credentials.json` with GitHub while maintaining security (i.e. without uploading the private keys on public repo...make them environment variables?, [via github secrets tokens?](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) cannot use a full json in github secrets)
- [ ] share access with lab members to update as necessary
- [ ] python script using Google Sheets API ([some instructions here](https://towardsdatascience.com/use-google-sheets-s3-and-python-to-build-a-website-quickly-8e4501dab02e)) to access sheet and update the YAML files in `_data/`
- [ ] create a workflow in GitHub Actions
